// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dezazmpnpuwqwwzjdaiq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRlemF6bXBucHV3cXd3empkYWlxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1NTUxODUsImV4cCI6MjA2NDEzMTE4NX0.fstEXKqVRLW9pEV6EIfGxFXaq_1KzNb5hbHEmSshcdA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);